// src/shell/strings.uk.ts — усі рядки оболонки. Назва гри — «Дріл Мото».
export const strings = {
  title: 'Дріл Мото',
  main: { play: 'Грати', records: 'Рекорди', about: 'Про гру', exit: 'Вийти' },
  leagues: {
    heading: 'Ліга',
    names: ['Легка', 'Середня', 'Важка'] as const,
    progress: (done: number, total: number) => `${done} з ${total}`,
    locked: (left: number, prev: string) => `Пройди ще ${left} у лізі «${prev}»`,
    back: 'Назад',
  },
  tracks: { heading: (league: string) => `Треки · ${league}`, noBest: '—', locked: 'Закрито', back: 'До ліг' },
  race: {
    pause: 'Пауза',
    crashed: 'Падіння',
    restartIn: (s: number) => `Ще раз через ${s}…`,
    tapToRestart: 'Тап — одразу',
    fps: (n: number) => `${n} fps`, // лише з ?debug (Task 10)
  },
  pause: { heading: 'Пауза', resume: 'Продовжити', restart: 'Заново', tracks: 'До треків', exit: 'Вийти з гри' },
  finish: {
    heading: 'Фініш',
    time: 'Час',
    prevBest: 'Попередній рекорд',
    newBest: 'Новий рекорд',
    leagueUnlocked: 'Відкрито наступну лігу',
    next: 'Далі',
    restart: 'Заново',
    tracks: 'До треків',
  },
  records: {
    heading: 'Рекорди',
    reset: 'Скинути прогрес',
    confirm: 'Скинути весь прогрес? Це не скасувати.',
    yes: 'Скинути',
    no: 'Лишити',
    back: 'Назад',
  },
  about: {
    heading: 'Про гру',
    text: ['Дріл Мото — мототріал у стилі класики 2004 року.', 'Механіка — з відкритого порту gravity-defied-web (GPL-2.0).'],
    source: 'Наш код: github.com/ZhekaGrem/drill-moto',
    sourceUrl: 'https://github.com/ZhekaGrem/drill-moto',
    disclaimer: 'Гра не повʼязана з Codebrew Software; треки, графіка й назва — наші.',
    version: (v: string) => `Версія ${v}`,
    back: 'Назад',
  },
  controls: {
    back: '◀ назад',
    forward: 'вперед ▶',
    brake: 'гальмо',
    gas: 'ГАЗ',
    backAria: 'Нахил назад',
    forwardAria: 'Нахил вперед',
    brakeAria: 'Гальмо',
    gasAria: 'Газ',
    keys: '← → нахил · ↑ газ · ↓ гальмо · Esc пауза',
  },
} as const
